---
- name: Add VLAN to UCS
  ucs_vlans:
    fabric: common
    hostname: "{{ inventory_hostname }}"
    id: "{{ vlan_id }}"
    multicast_policy: "{{ multicast_policy }}"
    name: "{{ vlan_name }}"
    password: "{{ ucs_mgr_password }}"
    username: "{{ ucs_mgr_username }}"
  delegate_to: localhost
  when: delete_vlan is not defined or not delete_vlan|bool
  tags:
    - ucs
    - vlan
    - ucs-vlan
    - add-vlan
    - add-ucs-vlan

- name: Add VLAN to vNIC templates
  ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    name: "{{ item }}"
    password: "{{ ucs_mgr_password }}"
    username: "{{ ucs_mgr_username }}"
    vlans_list:
      - name: "{{ vlan_name }}"
  delegate_to: localhost
  with_items: "{{ vnic_templates }}"
  when: delete_vlan is not defined or not delete_vlan|bool
  tags:
      - ucs
      - vlan
      - ucs-vlan
      - allow-vlan
      - allow-ucs-vlan

- name: Remove VLAN from vNIC templates
  ucs_vnic_template:
    hostname: "{{ inventory_hostname }}"
    name: "{{ item }}"
    password: "{{ ucs_mgr_password }}"
    username: "{{ ucs_mgr_username }}"
    vlans_list:
      - name: "{{ vlan_name }}"
        state: absent
  delegate_to: localhost
  with_items: "{{ vnic_templates }}"
  when: delete_vlan is defined and delete_vlan|bool
  tags:
      - ucs
      - vlan
      - ucs-vlan
      - remove-vlan
      - remove-ucs-vlan

- name: Delete VLAN from UCS
  ucs_vlans:
    fabric: common
    hostname: "{{ inventory_hostname }}"
    name: "{{ vlan_name }}"
    password: "{{ ucs_mgr_password }}"
    state: absent
    username: "{{ ucs_mgr_username }}"
  delegate_to: localhost
  when: delete_vlan is defined and delete_vlan|bool
  tags:
    - ucs
    - vlan
    - ucs-vlan
    - delete-vlan
    - delete-ucs-vlan
