---
- name: Add VLAN to UCS
  ucs_vlans:
    fabric: common
    hostname: "{{ inventory_hostname }}"
    id: "{{ vlan_id }}"
    multicast_policy: "{{ multicast_policy }}"
    name: "{{ vlan_name }}"
    password: "{{ ucs_mgr_password }}"
    username: "{{ ucs_mgr_username }}"
  delegate_to: localhost
  when: delete_vlan is not defined or not delete_vlan|bool
  tags:
    - ucs
    - vlan
    - ucs-vlan
    - add-vlan
    - add-ucs-vlan

- name: Delete VLAN from UCS
  ucs_vlans:
    fabric: common
    hostname: "{{ inventory_hostname }}"
    name: "{{ vlan_name }}"
    password: "{{ ucs_mgr_password }}"
    state: absent
    username: "{{ ucs_mgr_username }}"
  delegate_to: localhost
  when: delete_vlan is defined and delete_vlan|bool
  tags:
    - ucs
    - vlan
    - ucs-vlan
    - delete-vlan
    - delete-ucs-vlan
