---
- name: Set the list of VMware clusters
  set_fact: vm_clusters="{{ vm_clusters }} + [{{ item.key }}]"
  with_items: "{{ lookup('dict', cluster_vswitch) }}"
  when: vm_clusters is not defined
  tags:
    - vCenter
    - vlan
    - vmware-vlan
    - add-vlan
    - add-vmware-vlan
    - delete-vlan
    - delete-vmware-vlan

- name: Add VLAN to VMware cluster
  vmware_portgroup:
    hostname: "{{ inventory_hostname }}"
    cluster: "{{ item }}"
    switch: "{{ cluster_vswitch[item] }}"
    portgroup: "{{ vm_vlan_name }}"
    vlan_id: "{{ vlan_id }}"
    validate_certs: no
  delegate_to: localhost
  with_items: "{{ vm_clusters }}"
  when: delete_vlan is not defined or delete_vlan is False
  tags:
    - vcenter
    - vlan
    - vmware-vlan
    - add-vlan
    - add-vmware-vlan

- name: Delete VLAN from VMware cluster
  vmware_portgroup:
    hostname: "{{ inventory_hostname }}"
    cluster: "{{ item }}"
    state: absent
    switch: "{{ cluster_vswitch[item] }}"
    portgroup: "{{ vm_vlan_name }}"
    vlan_id: "{{ vlan_id }}"
    validate_certs: no
  delegate_to: localhost
  with_items: "{{ vm_clusters }}"
  when: delete_vlan is defined and delete_vlan is True
  tags:
    - vcenter
    - vlan
    - vmware-vlan
    - delete-vlan
    - delete-vmware-vlan
