---
- name: Ensure VM VLAN Name is defined
  fail:
      msg: "vm-vlan-name must be specified"
  when: vm_vlan_name is not defined
  tags:
    - vCenter
    - vlan
    - vmware-vlan
    - add-vlan
    - add-vmware-vlan
    - delete-vlan
    - delete-vmware-vlan

- name: Set the list of VMware clusters
  set_fact: vm_clusters="{{ cluster_vswitch | list }}"
  when: vm_clusters is not defined
  tags:
    - vCenter
    - vlan
    - vmware-vlan
    - add-vlan
    - add-vmware-vlan
    - delete-vlan
    - delete-vmware-vlan

- name: Add VLAN to VMware cluster
  vmware_portgroup:
    hostname: "{{ inventory_hostname }}"
    cluster: "{{ item }}"
    switch: "{{ cluster_vswitch[item] }}"
    portgroup: "{{ vm_vlan_name }}"
    vlan_id: "{{ vlan_id }}"
    validate_certs: no
  delegate_to: localhost
  with_items: "{{ vm_clusters }}"
  when: delete_vlan is not defined or not delete_vlan|bool
  tags:
    - vcenter
    - vlan
    - vmware-vlan
    - add-vlan
    - add-vmware-vlan

- name: Delete VLAN from VMware cluster
  vmware_portgroup:
    hostname: "{{ inventory_hostname }}"
    cluster: "{{ item }}"
    state: absent
    switch: "{{ cluster_vswitch[item] }}"
    portgroup: "{{ vm_vlan_name }}"
    vlan_id: "{{ vlan_id }}"
    validate_certs: no
  delegate_to: localhost
  with_items: "{{ vm_clusters }}"
  when: delete_vlan is defined and delete_vlan|bool
  tags:
    - vcenter
    - vlan
    - vmware-vlan
    - delete-vlan
    - delete-vmware-vlan
