---
# This file holds variables relevant to all sites and devices.
#

# This should always be "nxos".
ansible_network_os: nxos

# Core variables
core_hsrp_vip_v4_suffix: "254"
core_hsrp_vip_v6_suffix: "fe"
core_hsrp_v4_track: "3"
core_hsrp_v6_track: "5"
