# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mac_metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.100.253.13:8081']
        labels:
          service_name: idf_mac_address_count

  - job_name: 'hx_metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.100.253.13:8082']
        labels:
          service_name: hx_read_write_stats

  - job_name: 'dhcp_metrics'
    scrape_interval: 1m
    static_configs:
       - targets: ['10.100.253.13:8083']
         labels:
           service_name: dhcp_server_stats

  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 10.128.0.1
        - 10.128.0.2
        - 10.128.0.5
        - 10.128.0.6
        - 10.128.0.7
        - 10.128.0.9
        - 10.128.0.10
        - 10.127.0.61
        - 10.127.0.62
        - 10.127.0.101
        - 10.127.0.102
        - 10.127.0.103
        - 10.127.0.104
        - 10.127.0.105
        - 10.127.0.106
        - 10.127.0.107
        - 10.127.0.108
        - 10.127.0.109
        - 10.127.0.110
        - 10.127.0.111
        - 10.127.0.112
        - 10.127.0.113
        - 10.127.0.114
        - 10.127.0.115
        - 10.127.0.116
        - 10.127.0.242
        - 10.127.0.243
        - 10.127.0.244
        - 10.127.0.252
        - 10.127.0.253
        - 10.127.0.247
        - 10.127.0.248
        - 10.127.0.249
        - 10.127.0.250
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
