# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mac_metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.100.252.13:8081']
        labels:
          service_name: idf_mac_address_count

  - job_name: 'hx_metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.100.252.13:8082']
        labels:
          service_name: hx_read_write_stats

  - job_name: 'dhcp_metrics'
    scrape_interval: 1m
    static_configs:
       - targets: ['10.100.252.13:8083']
         labels:
           service_name: dhcp_server_stats

  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 006-mdf-a.ciscolive.network
        - 007-mdf-a.ciscolive.network
        - core1-wb.ciscolive.network
        - core2-wa.ciscolive.network
        - core1-l3c.ciscolive.network
        - 008-mdf-a.ciscolive.network
        - 004-mdf-a.ciscolive.network
        - core2-wb.ciscolive.network
        - core1-edge.ciscolive.network
        - 006-mdf-b.ciscolive.network
        - 008-mdf-b.ciscolive.network
        - core1-wa.ciscolive.network
        - core2-ts.ciscolive.network
        - 003-mdf-b.ciscolive.network
        - fusion-005-mdf-a.ciscolive.network
        - fusion-005-mdf-b.ciscolive.network
        - 005-mdf-a.ciscolive.network
        - 005-mdf-b.ciscolive.network
        - 004-mdf-b.ciscolive.network
        - core1-ts.ciscolive.network
        - core2-edge.ciscolive.network
        - dc2-ethsw-1.ciscolive.network
        - dc2-ethsw-2.ciscolive.network
        - dc1-ethsw-1.ciscolive.network
        - dc1-ethsw-2.ciscolive.network
        - 003-mdf-a.ciscolive.network
        - core2-l3c.ciscolive.network
        - 007-mdf-b.ciscolive.network
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
