{
 "title": "DHCP Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "DHCP Active Leases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activeLeases{server=\"10.100.253.9\"}",
     "legendFormat": "DC1-DHCP"
    },
    {
     "expr": "activeLeases{server=\"10.100.254.9\"}",
     "legendFormat": "DC2-DHCP"
    }
   ]
  },
  {
   "title": "DHCP Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Counts Per Second" }
   ],
   "targets": [
    {
     "expr": "irate(discovers{server=\"10.100.253.9\"}[30m])",
     "legendFormat": "DC1-DHCP Discovers"
    },
    {
     "expr": "irate(discovers{server=\"10.100.254.9\"}[30m])",
     "legendFormat": "DC2-DHCP Discovers"
    },
    {
     "expr": "acksPerSecond{server=\"10.100.253.9\"}",
     "legendFormat": "DC1-DHCP Acks"
    },
    {
     "expr": "acksPerSecond{server=\"10.100.254.9\"}",
     "legendFormat": "DC2-DHCP Acks"
    },
    {
     "expr": "irate(offers{server=\"10.100.253.9\"}[30m])",
     "legendFormat": "DC1-DHCP Offers"
    },
    {
     "expr": "irate(offers{server=\"10.100.253.109\"}[30m])",
     "legendFormat": "DC2-DHCP Offers"
    },
    {
     "expr": "irate(droppedTotal{server=\"10.100.253.9\"}[30m])",
     "legendFormat": "DC1-DHCP Dropped"
    },
    {
     "expr": "irate(droppedTotal{server=\"10.100.254.9\"}[30m])",
     "legendFormat": "DC2-DHCP Dropped"
    },
    {
     "expr": "irate(requests{server=\"10.100.253.9\"}[30m])",
     "legendFormat": "DC1-DHCP Requests"
    },
    {
     "expr": "irate(requests{server=\"10.100.254.9\"}[30m])",
     "legendFormat": "DC2-DHCP Requests"
    }
   ]
  },
  {
   "title": "CPNR Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "diskUtilization{server=\"dc1-dhcp.ciscolive.network\"}",
     "legendFormat": "DC1-DHCP"
    },
    {
     "expr": "diskUtilization{server=\"dc2-dhcp.ciscolive.network\"}",
     "legendFormat": "DC2-DHCP"
    },
    {
     "expr": "diskUtilization{server=\"dc1-dns.ciscolive.network\"}",
     "legendFormat": "DC1-DNS"
    },
    {
     "expr": "diskUtilization{server=\"dc2-dhcp.ciscolive.network\"}",
     "legendFormat": "DC2-DNS"
    }
   ]
  }
 ]
}