{
 "title": "GPU Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 40pt; align: center\">NOC AI - Powered By UCS X Direct and Nvidia L40S GPUs</span>"
   }
  },
  {
   "title": "Total GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_utilization_pct{instance=~\".*ciscolive.network$\"}) / 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total GPU Power Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpu_power_usage{instance=~\".*ciscolive.network$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_pct{instance=~\".*ciscolive.network$\"}",
     "legendFormat": "{{instance}} GPU {{device}}"
    }
   ]
  },
  {
   "title": "GPU Utilization Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "gpu_utilization_pct", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_usage{instance=~\".*ciscolive.network$\"}",
     "legendFormat": "{{instance}} GPU {{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 10, "x": 13, "y": 25 },
   "options": {
    "content": "<img src=\"https://cl-freebsd.ciscolive.network/~jclarke/chatnoc.png\"/>"
   }
  }
 ]
}