{
 "title": "HX - Horizontal",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HyperFlex Statistics - left: last 6h, right: last 1min",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "MBps_Write{host=\"10.127.253.85\"}",
     "legendFormat": "Write Throughput HX-1"
    },
    {
     "expr": "MBps_Read{host=\"10.127.253.85\"}",
     "legendFormat": "Read Throughput HX-1"
    },
    {
     "expr": "MBps_Write{host=\"10.127.254.85\"}",
     "legendFormat": "Write Throughput HX-2"
    },
    {
     "expr": "MBps_Read{host=\"10.127.254.85\"}",
     "legendFormat": "Read Throughput HX-2"
    }
   ]
  },
  {
   "title": "Read Throughput HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "MBps_Read{host='10.127.253.85'}"
    }
   ]
  },
  {
   "title": "Read IOPS HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "IOPS_Read{host='10.127.253.85'}"
    }
   ]
  },
  {
   "title": "Read Latency HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "Lat_Read{host='10.127.253.85'}" }
   ]
  },
  {
   "title": "Write Throughput HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "MBps_Write{host='10.127.253.85'}"
    }
   ]
  },
  {
   "title": "Write IOPS HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "IOPS_Write{host='10.127.253.85'}"
    }
   ]
  },
  {
   "title": "Write Latency HX-1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Lat_Write{host='10.127.253.85'}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "IOPS_Read{host='10.127.253.85'}",
     "legendFormat": "IOPS Read HX-1"
    },
    {
     "expr": "IOPS_Write{host='10.127.253.85'}",
     "legendFormat": "IOPS Write HX-1"
    },
    {
     "expr": "IOPS_Read{host='10.127.254.85'}",
     "legendFormat": "IOPS Read HX-2"
    },
    {
     "expr": "IOPS_Write{host='10.127.254.85'}",
     "legendFormat": "IOPS Write HX-2"
    }
   ]
  },
  {
   "title": "Read Throughput HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "MBps_Read{host='10.127.254.85'}"
    }
   ]
  },
  {
   "title": "Read IOPS HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "IOPS_Read{host='10.127.254.85'}"
    }
   ]
  },
  {
   "title": "Read Latency HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "Lat_Read{host='10.127.254.85'}" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "Lat_Read{host='10.127.253.85'}", "legendFormat": "Latency Read HX-1" },
    {
     "expr": "Lat_Write{host='10.127.253.85'}",
     "legendFormat": "Latency Write HX-1"
    },
    { "expr": "Lat_Read{host='10.127.254.85'}", "legendFormat": "Latency Read HX-2" },
    {
     "expr": "Lat_Write{host='10.127.254.85'}",
     "legendFormat": "Latency Write HX-2"
    }
   ]
  },
  {
   "title": "Write Throughput HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "MBps_Write{host='10.127.254.85'}"
    }
   ]
  },
  {
   "title": "Write IOPS HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "IOPS_Write{host='10.127.254.85'}"
    }
   ]
  },
  {
   "title": "Write Latency HX-2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Lat_Write{host='10.127.254.85'}"
    }
   ]
  }
 ]
}