{
 "title": "Internal MAC, ARP, ND, NAT, QFP Counts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "CORE1-EDGE DNS NAT Translations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "umbrella1NatTrans{idf=\"CORE1-EDGE\"}",
     "legendFormat": "DC1-UMBRELLA"
    },
    {
     "expr": "umbrella2NatTrans{idf=\"CORE1-EDGE\"}",
     "legendFormat": "DC2-UMBRELLA"
    }
   ]
  },
  {
   "title": "Edge QFP Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "qfpUtil{idf=\"CORE1-EDGE\"}",
     "legendFormat": "CORE1-EDGE QFP Utilization"
    },
    {
     "expr": "qfpUtil{idf=\"CORE2-EDGE\"}",
     "legendFormat": "CORE2-EDGE QFP Utilization"
    }
   ]
  },
  {
   "title": "Edge NAT Translations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "natTranslations{idf=\"CORE1-EDGE\"}",
     "legendFormat": "CORE1-EDGE NAT Translations"
    },
    {
     "expr": "natTranslations{idf=\"CORE2-EDGE\"}",
     "legendFormat": "CORE2-EDGE NAT Tranlsations"
    }
   ]
  },
  {
   "title": "WA MAC Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "totalMacs{idf=\"CORE1-WA\"}",
     "legendFormat": "CORE1-WA"
    },
    {
     "expr": "totalMacs{idf=\"CORE2-WA\"}",
     "legendFormat": "CORE2-WA"
    }
   ]
  },
  {
   "title": "WA ARP Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arpEntries{idf=\"CORE1-WA\"}",
     "legendFormat": "CORE1-WA"
    },
    {
     "expr": "arpEntries{idf=\"CORE2-WA\"}",
     "legendFormat": "CORE2-WA"
    }
   ]
  },
  {
   "title": "WA ND Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndEntries{idf=\"CORE1-WA\"}",
     "legendFormat": "CORE1-WA"
    },
    {
     "expr": "ndEntries{idf=\"CORE2-WA\"}",
     "legendFormat": "CORE2-WA"
    }
   ]
  },
  {
   "title": "IDF MAC Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Dynamic MAC Addresses" }
   ],
   "targets": [
    {
     "expr": "totalMacs{idf=\"008-x42.ciscolive.network\"}",
     "legendFormat": "008-X42"
    },
    {
     "expr": "totalMacs{idf=\"007-x11.ciscolive.network\"}",
     "legendFormat": "007-X11"
    },
    {
     "expr": "totalMacs{idf=\"007-x13.ciscolive.network\"}",
     "legendFormat": "007-X13"
    },
    {
     "expr": "totalMacs{idf=\"008-x49.ciscolive.network\"}",
     "legendFormat": "008-X49"
    },
    {
     "expr": "totalMacs{idf=\"008-x53.ciscolive.network\"}",
     "legendFormat": "008-X53"
    },
    {
     "expr": "totalMacs{idf=\"003-x33.ciscolive.network\"}",
     "legendFormat": "003-X33"
    },
    {
     "expr": "totalMacs{idf=\"008-x36.ciscolive.network\"}",
     "legendFormat": "008-X36"
    },
    {
     "expr": "totalMacs{idf=\"008-x37.ciscolive.network\"}",
     "legendFormat": "008-X37"
    },
    {
     "expr": "totalMacs{idf=\"006-x23.ciscolive.network\"}",
     "legendFormat": "006-X23"
    },
    {
     "expr": "totalMacs{idf=\"008-x52.ciscolive.network\"}",
     "legendFormat": "008-X52"
    },
    {
     "expr": "totalMacs{idf=\"003-x02.ciscolive.network\"}",
     "legendFormat": "003-X02"
    },
    {
     "expr": "totalMacs{idf=\"003-x55.ciscolive.network\"}",
     "legendFormat": "003-X55"
    },
    {
     "expr": "totalMacs{idf=\"007-x09.ciscolive.network\"}",
     "legendFormat": "007-X09"
    },
    {
     "expr": "totalMacs{idf=\"006-x20.ciscolive.network\"}",
     "legendFormat": "006-X20"
    },
    {
     "expr": "totalMacs{idf=\"008-x39.ciscolive.network\"}",
     "legendFormat": "008-X39"
    },
    {
     "expr": "totalMacs{idf=\"008-x41.ciscolive.network\"}",
     "legendFormat": "008-X41"
    },
    {
     "expr": "totalMacs{idf=\"003-x54.ciscolive.network\"}",
     "legendFormat": "003-X54"
    },
    {
     "expr": "totalMacs{idf=\"004-x07.ciscolive.network\"}",
     "legendFormat": "004-X07"
    },
    {
     "expr": "totalMacs{idf=\"006-x22.ciscolive.network\"}",
     "legendFormat": "006-X22"
    },
    {
     "expr": "totalMacs{idf=\"006-x27.ciscolive.network\"}",
     "legendFormat": "006-X27"
    },
    {
     "expr": "totalMacs{idf=\"008-x47.ciscolive.network\"}",
     "legendFormat": "008-X47"
    },
    {
     "expr": "totalMacs{idf=\"006-x19.ciscolive.network\"}",
     "legendFormat": "006-X19"
    },
    {
     "expr": "totalMacs{idf=\"008-x46.ciscolive.network\"}",
     "legendFormat": "008-X46"
    },
    {
     "expr": "totalMacs{idf=\"008-x38.ciscolive.network\"}",
     "legendFormat": "008-X38"
    },
    {
     "expr": "totalMacs{idf=\"008-x40.ciscolive.network\"}",
     "legendFormat": "008-X40"
    },
    {
     "expr": "totalMacs{idf=\"008-x43.ciscolive.network\"}",
     "legendFormat": "008-X43"
    },
    {
     "expr": "totalMacs{idf=\"007-x15.ciscolive.network\"}",
     "legendFormat": "007-X15"
    },
    {
     "expr": "totalMacs{idf=\"006-x18.ciscolive.network\"}",
     "legendFormat": "006-X18"
    },
    {
     "expr": "totalMacs{idf=\"006-x29.ciscolive.network\"}",
     "legendFormat": "006-X29"
    },
    {
     "expr": "totalMacs{idf=\"006-x24.ciscolive.network\"}",
     "legendFormat": "006-X24"
    },
    {
     "expr": "totalMacs{idf=\"007-x12.ciscolive.network\"}",
     "legendFormat": "007-X12"
    },
    {
     "expr": "totalMacs{idf=\"008-x45.ciscolive.network\"}",
     "legendFormat": "008-X45"
    },
    {
     "expr": "totalMacs{idf=\"006-x28.ciscolive.network\"}",
     "legendFormat": "006-X28"
    },
    {
     "expr": "totalMacs{idf=\"007-x16.ciscolive.network\"}",
     "legendFormat": "007-X16"
    },
    {
     "expr": "totalMacs{idf=\"006-x25.ciscolive.network\"}",
     "legendFormat": "006-X25"
    },
    {
     "expr": "totalMacs{idf=\"006-x30.ciscolive.network\"}",
     "legendFormat": "006-X30"
    },
    {
     "expr": "totalMacs{idf=\"007-x10.ciscolive.network\"}",
     "legendFormat": "007-X10"
    },
    {
     "expr": "totalMacs{idf=\"008-x44.ciscolive.network\"}",
     "legendFormat": "008-X44"
    },
    {
     "expr": "totalMacs{idf=\"003-x35.ciscolive.network\"}",
     "legendFormat": "003-X35"
    },
    {
     "expr": "totalMacs{idf=\"006-x21.ciscolive.network\"}",
     "legendFormat": "006-X21"
    },
    {
     "expr": "totalMacs{idf=\"006-x26.ciscolive.network\"}",
     "legendFormat": "006-X26"
    },
    {
     "expr": "totalMacs{idf=\"006-x31.ciscolive.network\"}",
     "legendFormat": "006-X31"
    },
    {
     "expr": "totalMacs{idf=\"007-x14.ciscolive.network\"}",
     "legendFormat": "007-X14"
    },
    {
     "expr": "totalMacs{idf=\"003-x17.ciscolive.network\"}",
     "legendFormat": "003-X17"
    }
   ]
  },
  {
   "title": "IDF ARP Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arpEntries{idf=\"008-x42.ciscolive.network\"}",
     "legendFormat": "008-X42"
    },
    {
     "expr": "arpEntries{idf=\"007-x11.ciscolive.network\"}",
     "legendFormat": "007-X11"
    },
    {
     "expr": "arpEntries{idf=\"007-x13.ciscolive.network\"}",
     "legendFormat": "007-X13"
    },
    {
     "expr": "arpEntries{idf=\"008-x49.ciscolive.network\"}",
     "legendFormat": "008-X49"
    },
    {
     "expr": "arpEntries{idf=\"008-x53.ciscolive.network\"}",
     "legendFormat": "008-X53"
    },
    {
     "expr": "arpEntries{idf=\"003-x33.ciscolive.network\"}",
     "legendFormat": "003-X33"
    },
    {
     "expr": "arpEntries{idf=\"008-x36.ciscolive.network\"}",
     "legendFormat": "008-X36"
    },
    {
     "expr": "arpEntries{idf=\"008-x37.ciscolive.network\"}",
     "legendFormat": "008-X37"
    },
    {
     "expr": "arpEntries{idf=\"006-x23.ciscolive.network\"}",
     "legendFormat": "006-X23"
    },
    {
     "expr": "arpEntries{idf=\"008-x52.ciscolive.network\"}",
     "legendFormat": "008-X52"
    },
    {
     "expr": "arpEntries{idf=\"003-x02.ciscolive.network\"}",
     "legendFormat": "003-X02"
    },
    {
     "expr": "arpEntries{idf=\"003-x55.ciscolive.network\"}",
     "legendFormat": "003-X55"
    },
    {
     "expr": "arpEntries{idf=\"007-x09.ciscolive.network\"}",
     "legendFormat": "007-X09"
    },
    {
     "expr": "arpEntries{idf=\"006-x20.ciscolive.network\"}",
     "legendFormat": "006-X20"
    },
    {
     "expr": "arpEntries{idf=\"008-x39.ciscolive.network\"}",
     "legendFormat": "008-X39"
    },
    {
     "expr": "arpEntries{idf=\"008-x41.ciscolive.network\"}",
     "legendFormat": "008-X41"
    },
    {
     "expr": "arpEntries{idf=\"003-x54.ciscolive.network\"}",
     "legendFormat": "003-X54"
    },
    {
     "expr": "arpEntries{idf=\"004-x07.ciscolive.network\"}",
     "legendFormat": "004-X07"
    },
    {
     "expr": "arpEntries{idf=\"006-x22.ciscolive.network\"}",
     "legendFormat": "006-X22"
    },
    {
     "expr": "arpEntries{idf=\"006-x27.ciscolive.network\"}",
     "legendFormat": "006-X27"
    },
    {
     "expr": "arpEntries{idf=\"008-x47.ciscolive.network\"}",
     "legendFormat": "008-X47"
    },
    {
     "expr": "arpEntries{idf=\"006-x19.ciscolive.network\"}",
     "legendFormat": "006-X19"
    },
    {
     "expr": "arpEntries{idf=\"008-x46.ciscolive.network\"}",
     "legendFormat": "008-X46"
    },
    {
     "expr": "arpEntries{idf=\"008-x38.ciscolive.network\"}",
     "legendFormat": "008-X38"
    },
    {
     "expr": "arpEntries{idf=\"008-x40.ciscolive.network\"}",
     "legendFormat": "008-X40"
    },
    {
     "expr": "arpEntries{idf=\"008-x43.ciscolive.network\"}",
     "legendFormat": "008-X43"
    },
    {
     "expr": "arpEntries{idf=\"007-x15.ciscolive.network\"}",
     "legendFormat": "007-X15"
    },
    {
     "expr": "arpEntries{idf=\"006-x18.ciscolive.network\"}",
     "legendFormat": "006-X18"
    },
    {
     "expr": "arpEntries{idf=\"006-x29.ciscolive.network\"}",
     "legendFormat": "006-X29"
    },
    {
     "expr": "arpEntries{idf=\"006-x24.ciscolive.network\"}",
     "legendFormat": "006-X24"
    },
    {
     "expr": "arpEntries{idf=\"007-x12.ciscolive.network\"}",
     "legendFormat": "007-X12"
    },
    {
     "expr": "arpEntries{idf=\"008-x45.ciscolive.network\"}",
     "legendFormat": "008-X45"
    },
    {
     "expr": "arpEntries{idf=\"006-x28.ciscolive.network\"}",
     "legendFormat": "006-X28"
    },
    {
     "expr": "arpEntries{idf=\"007-x16.ciscolive.network\"}",
     "legendFormat": "007-X16"
    },
    {
     "expr": "arpEntries{idf=\"006-x25.ciscolive.network\"}",
     "legendFormat": "006-X25"
    },
    {
     "expr": "arpEntries{idf=\"006-x30.ciscolive.network\"}",
     "legendFormat": "006-X30"
    },
    {
     "expr": "arpEntries{idf=\"007-x10.ciscolive.network\"}",
     "legendFormat": "007-X10"
    },
    {
     "expr": "arpEntries{idf=\"008-x44.ciscolive.network\"}",
     "legendFormat": "008-X44"
    },
    {
     "expr": "arpEntries{idf=\"003-x35.ciscolive.network\"}",
     "legendFormat": "003-X35"
    },
    {
     "expr": "arpEntries{idf=\"006-x21.ciscolive.network\"}",
     "legendFormat": "006-X21"
    },
    {
     "expr": "arpEntries{idf=\"006-x26.ciscolive.network\"}",
     "legendFormat": "006-X26"
    },
    {
     "expr": "arpEntries{idf=\"006-x31.ciscolive.network\"}",
     "legendFormat": "006-X31"
    },
    {
     "expr": "arpEntries{idf=\"007-x14.ciscolive.network\"}",
     "legendFormat": "007-X14"
    },
    {
     "expr": "arpEntries{idf=\"003-x17.ciscolive.network\"}",
     "legendFormat": "003-X17"
    },
    { "legendFormat": "CORE1-L3C" },
    {}
   ]
  },
  {
   "title": "IDF ND Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndEntries{idf=\"008-x42.ciscolive.network\"}",
     "legendFormat": "008-X42"
    },
    {
     "expr": "ndEntries{idf=\"007-x11.ciscolive.network\"}",
     "legendFormat": "007-X11"
    },
    {
     "expr": "ndEntries{idf=\"007-x13.ciscolive.network\"}",
     "legendFormat": "007-X13"
    },
    {
     "expr": "ndEntries{idf=\"008-x49.ciscolive.network\"}",
     "legendFormat": "008-X49"
    },
    {
     "expr": "ndEntries{idf=\"008-x53.ciscolive.network\"}",
     "legendFormat": "008-X53"
    },
    {
     "expr": "ndEntries{idf=\"003-x33.ciscolive.network\"}",
     "legendFormat": "003-X33"
    },
    {
     "expr": "ndEntries{idf=\"008-x36.ciscolive.network\"}",
     "legendFormat": "008-X36"
    },
    {
     "expr": "ndEntries{idf=\"008-x37.ciscolive.network\"}",
     "legendFormat": "008-X37"
    },
    {
     "expr": "ndEntries{idf=\"006-x23.ciscolive.network\"}",
     "legendFormat": "006-X23"
    },
    {
     "expr": "ndEntries{idf=\"008-x52.ciscolive.network\"}",
     "legendFormat": "008-X52"
    },
    {
     "expr": "ndEntries{idf=\"003-x02.ciscolive.network\"}",
     "legendFormat": "003-X02"
    },
    {
     "expr": "ndEntries{idf=\"003-x55.ciscolive.network\"}",
     "legendFormat": "003-X55"
    },
    {
     "expr": "ndEntries{idf=\"007-x09.ciscolive.network\"}",
     "legendFormat": "007-X09"
    },
    {
     "expr": "ndEntries{idf=\"006-x20.ciscolive.network\"}",
     "legendFormat": "006-X20"
    },
    {
     "expr": "ndEntries{idf=\"008-x39.ciscolive.network\"}",
     "legendFormat": "008-X39"
    },
    {
     "expr": "ndEntries{idf=\"008-x41.ciscolive.network\"}",
     "legendFormat": "008-X41"
    },
    {
     "expr": "ndEntries{idf=\"003-x54.ciscolive.network\"}",
     "legendFormat": "003-X54"
    },
    {
     "expr": "ndEntries{idf=\"004-x07.ciscolive.network\"}",
     "legendFormat": "004-X07"
    },
    {
     "expr": "ndEntries{idf=\"006-x22.ciscolive.network\"}",
     "legendFormat": "006-X22"
    },
    {
     "expr": "ndEntries{idf=\"006-x27.ciscolive.network\"}",
     "legendFormat": "006-X27"
    },
    {
     "expr": "ndEntries{idf=\"008-x47.ciscolive.network\"}",
     "legendFormat": "008-X47"
    },
    {
     "expr": "ndEntries{idf=\"006-x19.ciscolive.network\"}",
     "legendFormat": "006-X19"
    },
    {
     "expr": "ndEntries{idf=\"008-x46.ciscolive.network\"}",
     "legendFormat": "008-X46"
    },
    {
     "expr": "ndEntries{idf=\"008-x38.ciscolive.network\"}",
     "legendFormat": "008-X38"
    },
    {
     "expr": "ndEntries{idf=\"008-x40.ciscolive.network\"}",
     "legendFormat": "008-X40"
    },
    {
     "expr": "ndEntries{idf=\"008-x43.ciscolive.network\"}",
     "legendFormat": "008-X43"
    },
    {
     "expr": "ndEntries{idf=\"007-x15.ciscolive.network\"}",
     "legendFormat": "007-X15"
    },
    {
     "expr": "ndEntries{idf=\"006-x18.ciscolive.network\"}",
     "legendFormat": "006-X18"
    },
    {
     "expr": "ndEntries{idf=\"006-x29.ciscolive.network\"}",
     "legendFormat": "006-X29"
    },
    {
     "expr": "ndEntries{idf=\"006-x24.ciscolive.network\"}",
     "legendFormat": "006-X24"
    },
    {
     "expr": "ndEntries{idf=\"007-x12.ciscolive.network\"}",
     "legendFormat": "007-X12"
    },
    {
     "expr": "ndEntries{idf=\"008-x45.ciscolive.network\"}",
     "legendFormat": "008-X45"
    },
    {
     "expr": "ndEntries{idf=\"006-x28.ciscolive.network\"}",
     "legendFormat": "006-X28"
    },
    {
     "expr": "ndEntries{idf=\"007-x16.ciscolive.network\"}",
     "legendFormat": "007-X16"
    },
    {
     "expr": "ndEntries{idf=\"006-x25.ciscolive.network\"}",
     "legendFormat": "006-X25"
    },
    {
     "expr": "ndEntries{idf=\"006-x30.ciscolive.network\"}",
     "legendFormat": "006-X30"
    },
    {
     "expr": "ndEntries{idf=\"007-x10.ciscolive.network\"}",
     "legendFormat": "007-X10"
    },
    {
     "expr": "ndEntries{idf=\"008-x44.ciscolive.network\"}",
     "legendFormat": "008-X44"
    },
    {
     "expr": "ndEntries{idf=\"003-x35.ciscolive.network\"}",
     "legendFormat": "003-X35"
    },
    {
     "expr": "ndEntries{idf=\"006-x21.ciscolive.network\"}",
     "legendFormat": "006-X21"
    },
    {
     "expr": "ndEntries{idf=\"006-x26.ciscolive.network\"}",
     "legendFormat": "006-X26"
    },
    {
     "expr": "ndEntries{idf=\"006-x31.ciscolive.network\"}",
     "legendFormat": "006-X31"
    },
    {
     "expr": "ndEntries{idf=\"007-x14.ciscolive.network\"}",
     "legendFormat": "007-X14"
    },
    {
     "expr": "ndEntries{idf=\"003-x17.ciscolive.network\"}",
     "legendFormat": "003-X17"
    },
    { "legendFormat": "CORE1-L3C" },
    {}
   ]
  },
  {
   "title": "UMBRELLA NAT Translations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "umbrella1NatTrans{idf=\"CORE1-EDGE\"}",
     "legendFormat": "CORE1-EDGE: DC1-UMBRELLA"
    },
    {
     "expr": "umbrella2NatTrans{idf=\"CORE1-EDGE\"}",
     "legendFormat": "CORE1-EDGE: DC2-UMBRELLA"
    },
    {
     "expr": "umbrella1NatTrans{idf=\"CORE2-EDGE\"}",
     "legendFormat": "CORE2-EDGE: DC1-UMBRELLA"
    },
    {
     "expr": "umbrella2NatTrans{idf=\"CORE2-EDGE\"}",
     "legendFormat": "CORE2-EDGE: DC2-UMBRELLA"
    }
   ]
  }
 ]
}