{
 "title": "Pow! Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;UCS-X Power</h1>\n\n<img src=\"https://cl-freebsd.ciscolive.network/~anjesani/X-Series_Unbox_Image.png\"/>"
   }
  },
  {
   "title": "DC1 UCS-X Series Chassis",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu1\", label=\"UCS-X1\"}",
     "legendFormat": "UCS-X PSU1"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu1\", label=\"UCS-X2\"}",
     "legendFormat": "UCS-X PSU2"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu1\", label=\"UCS-X3\"}",
     "legendFormat": "UCS-X PSU3"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu2\", label=\"UCS-X4\"}",
     "legendFormat": "UCS-X PSU4"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu2\", label=\"UCS-X5\"}",
     "legendFormat": "UCS-X PSU5"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu2\", label=\"UCS-X6\"}",
     "legendFormat": "UCS-X PSU6"
    }
   ]
  },
  {
   "title": "DC2 UCS-X Series Chassis",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc2-pdu1\", label=\"UCS-X1\"}",
     "legendFormat": "UCS-X PSU1"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc2-pdu1\", label=\"UCS-X2\"}",
     "legendFormat": "UCS-X PSU2"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc2-pdu1\", label=\"UCS-X3\"}",
     "legendFormat": "UCS-X PSU3"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc2-pdu2\", connector_id=\"7\", label=\"UCS-X5\"}",
     "legendFormat": "UCS-X PSU4"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc1-pdu2\", label=\"UCS-X4\"}",
     "legendFormat": "UCS-X PSU5"
    },
    {
     "expr": "raritanpdu_activepower_watt{pdu=\"dc2-pdu2\", label=\"UCS-X5\"}",
     "legendFormat": "UCS-X PSU6"
    }
   ]
  },
  {
   "title": "DC PDU Power (0.0102741 watts per hamster)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=\"dc1-pdu1\", type=\"outlet\"})",
     "legendFormat": "{{pdu}} dc1-pdu1"
    },
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=\"dc1-pdu2\", type=\"outlet\"})",
     "legendFormat": "{{pdu}} dc1-pdu2"
    },
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=\"dc2-pdu1\", type=\"outlet\"})",
     "legendFormat": "{{pdu}} dc2-pdu1"
    },
    {
     "expr": "sum (rPDUIdentDevicePowerWatts{instance=\"dc2-pdu3.ciscolive.network\"}) + sum(raritanpdu_activepower_watt{pdu=\"dc2-pdu2\", type=\"outlet\"})",
     "legendFormat": "dc2-pdu2"
    }
   ]
  },
  {
   "title": "Core vs DC -  Lowest Power Usage Wins!",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=~\"dc[12]-pdu[12]\",type=\"outlet\"}) + sum (rPDUIdentDevicePowerWatts{instance=\"dc2-pdu3.ciscolive.network\"})",
     "legendFormat": "DC"
    },
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=~\"core[12]-pdu[12]\", type=\"outlet\"})",
     "legendFormat": "Core Network"
    }
   ]
  },
  {
   "title": "Core vs DC",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=~\"dc[12]-pdu[12]\",type=\"outlet\"}) + sum(raritanpdu_activepower_watt{pdu=\"dc2-pdu2\", type=\"outlet\"})",
     "legendFormat": "{{pdu}} DC"
    },
    {
     "expr": "sum(raritanpdu_activepower_watt{pdu=~\"core[12]-pdu[12]\",type=\"outlet\"})",
     "legendFormat": "{{pdu}} Core Network"
    }
   ]
  }
 ]
}