{
 "title": "Internet Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ZeroPoint", "query": "${VAR_ZEROPOINT}" },
   { "name": "IPv4ZeroPoint", "query": "${VAR_IPV4ZEROPOINT}" },
   { "name": "IPv6ZeroPoint", "query": "${VAR_IPV6ZEROPOINT}" }
  ]
 },
 "panels": [
  {
   "title": "Total IPv4 Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Internet Volume since Core Power-on",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"}) + sum(ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IPv6 Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of Total Intra-Network Traffic That Is IPv6",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}) / \n(sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}) + sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of Total Internet Traffic That Is IPv6",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}) / \n(sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}) + sum(ipIfStatsHCInOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"} + ipIfStatsHCOutOctets{instance=~\"core[1-2]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Internet Rate of Change over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum (irate(ipIfStatsHCInOctets{instance=~\"core[12]-edge.ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}[2m])*8)",
     "legendFormat": "Native IPv4 Download (not NAT64)"
    },
    {
     "expr": "sum (irate(ipIfStatsHCOutOctets{instance=~\"core[12]-edge.ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}[2m])*8)",
     "legendFormat": "Native IPv4 Upload (not NAT64)"
    },
    {
     "expr": "sum (irate(ipIfStatsHCInOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}[2m])*8)",
     "legendFormat": "{{instance}} IPv6 Download"
    },
    {
     "expr": "sum (irate(ipIfStatsHCOutOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}[2m])*8)",
     "legendFormat": "{{instance}} IPv6 Upload"
    }
   ]
  },
  {
   "title": "Total Internet Volume Growth over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(ipIfStatsHCInOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"}[2m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(avg_over_time(ipIfStatsHCOutOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"}[2m]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "NAT64 Traffic to IPv4-Only Hosts ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(ipIfStatsHCInOctets{ipIfStatsIPVersion=\"ipv4\", instance=~\"core[12]-nat64.ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"}[2m])*8)",
     "legendFormat": "NAT64 Download"
    },
    {
     "expr": "sum(irate(ipIfStatsHCOutOctets{ipIfStatsIPVersion=\"ipv4\", instance=~\"core[12]-nat64.ciscolive.network\",ifAlias=\"RAI BGP PEER LINK\"}[2m])*8)",
     "legendFormat": "NAT64 Upload"
    }
   ]
  },
  {
   "title": "Intra-Network Traffic Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum (irate(ipIfStatsHCInOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}[2m])*8)",
     "legendFormat": "Intra-network IPv4 Upload"
    },
    {
     "expr": "sum (irate(ipIfStatsHCOutOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv4\"}[2m])*8)",
     "legendFormat": "Intra-network IPv4 Download"
    },
    {
     "expr": "sum (irate(ipIfStatsHCInOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}[2m])*8)",
     "legendFormat": "Intra-network IPv6 Upload"
    },
    {
     "expr": "sum (irate(ipIfStatsHCOutOctets{instance=~\"core[12]-(edge|nat64).ciscolive.network\",ifAlias!=\"RAI BGP PEER LINK\",ipIfStatsIPVersion=\"ipv6\"}[2m])*8)",
     "legendFormat": "Intra-network IPv6 Download"
    }
   ]
  }
 ]
}